# Generated by Django 5.0.6 on 2024-06-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxmihoney', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.png', upload_to='profile_pics/'),
        ),
    ]
